### PR TITLE
pass correct project directory for immediate test fix #6657

### LINKED ISSUE #6657: avoid to rely on bash filename expansion in Jenkins tests
Somehow file name expansion works on lxplus, but not inside the containers we use for Jenkins jobs.

Actually it appears work when a filename containgin `*` is passed to
https://github.com/dmwm/CRABServer/blob/538a0309c76c7e79d5af38e36457ca7615f11bc1/test/testUtils.py#L48-L55
things work, 
but when it is passed to
https://github.com/dmwm/CRABServer/blob/538a0309c76c7e79d5af38e36457ca7615f11bc1/test/testUtils.py#L57-L64
it fails

### PR DESCRIPTION
**Pull request by ddaina**
fixes #6657. 

the only left test that is still failing is:

```
15:42:01 210616_134037:cmsbot_crab_sendExternalFolder
15:42:01 sendExternalFolder-testSubmit.sh /tmp/crabTestConfig/crab_sendExternalFolder
15:42:01 + workDir=/tmp/crabTestConfig/crab_sendExternalFolder
15:42:01 + lookInTaskSandboxFor '^external/' /tmp/crabTestConfig/crab_sendExternalFolder
15:42:01 + local 'file=^external/'
15:42:01 + local workDir=/tmp/crabTestConfig/crab_sendExternalFolder
15:42:01 ++ find /tmp/crabTestConfig/crab_sendExternalFolder/inputs -name '*default.tgz'
15:42:01 + tarball=/tmp/crabTestConfig/crab_sendExternalFolder/inputs/2b645042-c1f5-4bf5-852b-974be49fb404default.tgz
15:42:01 + tar tf /tmp/crabTestConfig/crab_sendExternalFolder/inputs/2b645042-c1f5-4bf5-852b-974be49fb404default.tgz
15:42:01 + grep -q '^external/'
15:42:01 + '[' 1 -ne 0 ']'
15:42:01 + exit 1
```

### CODE REVIEW

File: test/container/testingScripts/taskSubmission.sh [hunk 1]
```diff
@@ -32,20 +32,17 @@ submitTasks(){
 #run immediate check on tasks submitted for Client_Configuration_Validation testing. 
 #Save results to failed_tests and successful_tests files.
 immediateCheck(){
-  project_dir="/tmp/crabTestConfig"
   for task in ${tasksToCheck};
   do
 	echo ${task}
 	test_to_execute=`echo "${task}" | grep -oP '(?<=_crab_).*(?=)'`
-        task_dir=${project_dir}/${test_to_execute}
+	task_dir=`echo "${task}" | grep -oP '(?<=Project dir:\s).*(?=\sPlease)'`
```
Comment (belforte) [inline test/container/testingScripts/taskSubmission.sh:39]: can you explain a bit in comments what' done here ? can you start from a task name and find a project directory ? or... I am getting lost

Comment (ddaina) [reply test/container/testingScripts/taskSubmission.sh]: you are right. commit is bad and will not work. 
`${task}` represents a task name, e.g. `210616_134037:cmsbot_crab_sendExternalFolder`
given that `test_to_execute` will be `sendExternalFolder`
so `task_dir` has to be `task_dir=${project_dir}/crab_${test_to_execute}`

**Review by belforte — APPROVED** [review]

**Comment by belforte** [comment]
reads much better indeed !
